--CREATING A BACKUP
USE master;
GO

ALTER DATABASE INVENTORYDB1 
SET RECOVERY FULL
GO

USE master
GO

BACKUP DATABASE INVENTORYDB1
TO DISK = N'C:BACKUP\INVENTORYDB1.bak'
WITH NOFORMAT, NOINIT,
NAME = N'INVENTORYDB1-FULL DATABASE BACKUP', SKIP,NOREWIND,NOUNLOAD, STATS=100;
GO

